Update tasks.py
File "/opt/render/project/src/tasks.py", line 33, in <module>
    @Celery.task(bind=True)
     ~~~~~~~~~~~^^^^^^^^^^^
TypeError: Celery.task() missing 1 required positional argument: 'self'

had upercase celery intead of lower case